### ISSUE TITLE
package.yml/json

### ISSUE THREAD

**Issue by michaelkuty** [leonardo-modules/leonardo-package-index#10]
Finally I make dessicion that we cannot safety extract relevant data from packages and we must make extra file

package.yml

```
  name: leonardo-foo-bar
  widgets:
    FooWidget:
      icon: thum
      description: Long description
      homepage: url
  plugins:
    apps:
      name: Applications
```
